/*
FilterLists Directory API

An ASP.NET Core API serving the core FilterList information.

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// FilterListsDirectoryApiContractsModelsListDetailsVmViewUrlVm struct for FilterListsDirectoryApiContractsModelsListDetailsVmViewUrlVm
type FilterListsDirectoryApiContractsModelsListDetailsVmViewUrlVm struct {
	// The segment number of the URL for the FilterList (for multi-part lists).
	SegmentNumber *int32 `json:"segmentNumber,omitempty"`
	// How primary the URL is for the FilterList segment (1 is original, 2+ is a mirror; unique per SegmentNumber)
	Primariness *int32 `json:"primariness,omitempty"`
	// The view URL.
	Url *string `json:"url,omitempty"`
}

// NewFilterListsDirectoryApiContractsModelsListDetailsVmViewUrlVm instantiates a new FilterListsDirectoryApiContractsModelsListDetailsVmViewUrlVm object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFilterListsDirectoryApiContractsModelsListDetailsVmViewUrlVm() *FilterListsDirectoryApiContractsModelsListDetailsVmViewUrlVm {
	this := FilterListsDirectoryApiContractsModelsListDetailsVmViewUrlVm{}
	return &this
}

// NewFilterListsDirectoryApiContractsModelsListDetailsVmViewUrlVmWithDefaults instantiates a new FilterListsDirectoryApiContractsModelsListDetailsVmViewUrlVm object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFilterListsDirectoryApiContractsModelsListDetailsVmViewUrlVmWithDefaults() *FilterListsDirectoryApiContractsModelsListDetailsVmViewUrlVm {
	this := FilterListsDirectoryApiContractsModelsListDetailsVmViewUrlVm{}
	return &this
}

// GetSegmentNumber returns the SegmentNumber field value if set, zero value otherwise.
func (o *FilterListsDirectoryApiContractsModelsListDetailsVmViewUrlVm) GetSegmentNumber() int32 {
	if o == nil || isNil(o.SegmentNumber) {
		var ret int32
		return ret
	}
	return *o.SegmentNumber
}

// GetSegmentNumberOk returns a tuple with the SegmentNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FilterListsDirectoryApiContractsModelsListDetailsVmViewUrlVm) GetSegmentNumberOk() (*int32, bool) {
	if o == nil || isNil(o.SegmentNumber) {
    return nil, false
	}
	return o.SegmentNumber, true
}

// HasSegmentNumber returns a boolean if a field has been set.
func (o *FilterListsDirectoryApiContractsModelsListDetailsVmViewUrlVm) HasSegmentNumber() bool {
	if o != nil && !isNil(o.SegmentNumber) {
		return true
	}

	return false
}

// SetSegmentNumber gets a reference to the given int32 and assigns it to the SegmentNumber field.
func (o *FilterListsDirectoryApiContractsModelsListDetailsVmViewUrlVm) SetSegmentNumber(v int32) {
	o.SegmentNumber = &v
}

// GetPrimariness returns the Primariness field value if set, zero value otherwise.
func (o *FilterListsDirectoryApiContractsModelsListDetailsVmViewUrlVm) GetPrimariness() int32 {
	if o == nil || isNil(o.Primariness) {
		var ret int32
		return ret
	}
	return *o.Primariness
}

// GetPrimarinessOk returns a tuple with the Primariness field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FilterListsDirectoryApiContractsModelsListDetailsVmViewUrlVm) GetPrimarinessOk() (*int32, bool) {
	if o == nil || isNil(o.Primariness) {
    return nil, false
	}
	return o.Primariness, true
}

// HasPrimariness returns a boolean if a field has been set.
func (o *FilterListsDirectoryApiContractsModelsListDetailsVmViewUrlVm) HasPrimariness() bool {
	if o != nil && !isNil(o.Primariness) {
		return true
	}

	return false
}

// SetPrimariness gets a reference to the given int32 and assigns it to the Primariness field.
func (o *FilterListsDirectoryApiContractsModelsListDetailsVmViewUrlVm) SetPrimariness(v int32) {
	o.Primariness = &v
}

// GetUrl returns the Url field value if set, zero value otherwise.
func (o *FilterListsDirectoryApiContractsModelsListDetailsVmViewUrlVm) GetUrl() string {
	if o == nil || isNil(o.Url) {
		var ret string
		return ret
	}
	return *o.Url
}

// GetUrlOk returns a tuple with the Url field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FilterListsDirectoryApiContractsModelsListDetailsVmViewUrlVm) GetUrlOk() (*string, bool) {
	if o == nil || isNil(o.Url) {
    return nil, false
	}
	return o.Url, true
}

// HasUrl returns a boolean if a field has been set.
func (o *FilterListsDirectoryApiContractsModelsListDetailsVmViewUrlVm) HasUrl() bool {
	if o != nil && !isNil(o.Url) {
		return true
	}

	return false
}

// SetUrl gets a reference to the given string and assigns it to the Url field.
func (o *FilterListsDirectoryApiContractsModelsListDetailsVmViewUrlVm) SetUrl(v string) {
	o.Url = &v
}

func (o FilterListsDirectoryApiContractsModelsListDetailsVmViewUrlVm) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.SegmentNumber) {
		toSerialize["segmentNumber"] = o.SegmentNumber
	}
	if !isNil(o.Primariness) {
		toSerialize["primariness"] = o.Primariness
	}
	if !isNil(o.Url) {
		toSerialize["url"] = o.Url
	}
	return json.Marshal(toSerialize)
}

type NullableFilterListsDirectoryApiContractsModelsListDetailsVmViewUrlVm struct {
	value *FilterListsDirectoryApiContractsModelsListDetailsVmViewUrlVm
	isSet bool
}

func (v NullableFilterListsDirectoryApiContractsModelsListDetailsVmViewUrlVm) Get() *FilterListsDirectoryApiContractsModelsListDetailsVmViewUrlVm {
	return v.value
}

func (v *NullableFilterListsDirectoryApiContractsModelsListDetailsVmViewUrlVm) Set(val *FilterListsDirectoryApiContractsModelsListDetailsVmViewUrlVm) {
	v.value = val
	v.isSet = true
}

func (v NullableFilterListsDirectoryApiContractsModelsListDetailsVmViewUrlVm) IsSet() bool {
	return v.isSet
}

func (v *NullableFilterListsDirectoryApiContractsModelsListDetailsVmViewUrlVm) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFilterListsDirectoryApiContractsModelsListDetailsVmViewUrlVm(val *FilterListsDirectoryApiContractsModelsListDetailsVmViewUrlVm) *NullableFilterListsDirectoryApiContractsModelsListDetailsVmViewUrlVm {
	return &NullableFilterListsDirectoryApiContractsModelsListDetailsVmViewUrlVm{value: val, isSet: true}
}

func (v NullableFilterListsDirectoryApiContractsModelsListDetailsVmViewUrlVm) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFilterListsDirectoryApiContractsModelsListDetailsVmViewUrlVm) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


