/*
FilterLists Directory API

An ASP.NET Core API serving the core FilterList information.

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// FilterListsDirectoryApplicationQueriesGetTagsTagVm struct for FilterListsDirectoryApplicationQueriesGetTagsTagVm
type FilterListsDirectoryApplicationQueriesGetTagsTagVm struct {
	// The identifier.
	Id *int64 `json:"id,omitempty"`
	// The unique name.
	Name *string `json:"name,omitempty"`
	// The description.
	Description NullableString `json:"description,omitempty"`
	// The identifiers of the FilterLists to which this Tag is applied.
	FilterListIds []int64 `json:"filterListIds,omitempty"`
}

// NewFilterListsDirectoryApplicationQueriesGetTagsTagVm instantiates a new FilterListsDirectoryApplicationQueriesGetTagsTagVm object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFilterListsDirectoryApplicationQueriesGetTagsTagVm() *FilterListsDirectoryApplicationQueriesGetTagsTagVm {
	this := FilterListsDirectoryApplicationQueriesGetTagsTagVm{}
	return &this
}

// NewFilterListsDirectoryApplicationQueriesGetTagsTagVmWithDefaults instantiates a new FilterListsDirectoryApplicationQueriesGetTagsTagVm object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFilterListsDirectoryApplicationQueriesGetTagsTagVmWithDefaults() *FilterListsDirectoryApplicationQueriesGetTagsTagVm {
	this := FilterListsDirectoryApplicationQueriesGetTagsTagVm{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *FilterListsDirectoryApplicationQueriesGetTagsTagVm) GetId() int64 {
	if o == nil || isNil(o.Id) {
		var ret int64
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FilterListsDirectoryApplicationQueriesGetTagsTagVm) GetIdOk() (*int64, bool) {
	if o == nil || isNil(o.Id) {
    return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *FilterListsDirectoryApplicationQueriesGetTagsTagVm) HasId() bool {
	if o != nil && !isNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given int64 and assigns it to the Id field.
func (o *FilterListsDirectoryApplicationQueriesGetTagsTagVm) SetId(v int64) {
	o.Id = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *FilterListsDirectoryApplicationQueriesGetTagsTagVm) GetName() string {
	if o == nil || isNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FilterListsDirectoryApplicationQueriesGetTagsTagVm) GetNameOk() (*string, bool) {
	if o == nil || isNil(o.Name) {
    return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *FilterListsDirectoryApplicationQueriesGetTagsTagVm) HasName() bool {
	if o != nil && !isNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *FilterListsDirectoryApplicationQueriesGetTagsTagVm) SetName(v string) {
	o.Name = &v
}

// GetDescription returns the Description field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *FilterListsDirectoryApplicationQueriesGetTagsTagVm) GetDescription() string {
	if o == nil || isNil(o.Description.Get()) {
		var ret string
		return ret
	}
	return *o.Description.Get()
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *FilterListsDirectoryApplicationQueriesGetTagsTagVm) GetDescriptionOk() (*string, bool) {
	if o == nil {
    return nil, false
	}
	return o.Description.Get(), o.Description.IsSet()
}

// HasDescription returns a boolean if a field has been set.
func (o *FilterListsDirectoryApplicationQueriesGetTagsTagVm) HasDescription() bool {
	if o != nil && o.Description.IsSet() {
		return true
	}

	return false
}

// SetDescription gets a reference to the given NullableString and assigns it to the Description field.
func (o *FilterListsDirectoryApplicationQueriesGetTagsTagVm) SetDescription(v string) {
	o.Description.Set(&v)
}
// SetDescriptionNil sets the value for Description to be an explicit nil
func (o *FilterListsDirectoryApplicationQueriesGetTagsTagVm) SetDescriptionNil() {
	o.Description.Set(nil)
}

// UnsetDescription ensures that no value is present for Description, not even an explicit nil
func (o *FilterListsDirectoryApplicationQueriesGetTagsTagVm) UnsetDescription() {
	o.Description.Unset()
}

// GetFilterListIds returns the FilterListIds field value if set, zero value otherwise.
func (o *FilterListsDirectoryApplicationQueriesGetTagsTagVm) GetFilterListIds() []int64 {
	if o == nil || isNil(o.FilterListIds) {
		var ret []int64
		return ret
	}
	return o.FilterListIds
}

// GetFilterListIdsOk returns a tuple with the FilterListIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FilterListsDirectoryApplicationQueriesGetTagsTagVm) GetFilterListIdsOk() ([]int64, bool) {
	if o == nil || isNil(o.FilterListIds) {
    return nil, false
	}
	return o.FilterListIds, true
}

// HasFilterListIds returns a boolean if a field has been set.
func (o *FilterListsDirectoryApplicationQueriesGetTagsTagVm) HasFilterListIds() bool {
	if o != nil && !isNil(o.FilterListIds) {
		return true
	}

	return false
}

// SetFilterListIds gets a reference to the given []int64 and assigns it to the FilterListIds field.
func (o *FilterListsDirectoryApplicationQueriesGetTagsTagVm) SetFilterListIds(v []int64) {
	o.FilterListIds = v
}

func (o FilterListsDirectoryApplicationQueriesGetTagsTagVm) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !isNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if o.Description.IsSet() {
		toSerialize["description"] = o.Description.Get()
	}
	if !isNil(o.FilterListIds) {
		toSerialize["filterListIds"] = o.FilterListIds
	}
	return json.Marshal(toSerialize)
}

type NullableFilterListsDirectoryApplicationQueriesGetTagsTagVm struct {
	value *FilterListsDirectoryApplicationQueriesGetTagsTagVm
	isSet bool
}

func (v NullableFilterListsDirectoryApplicationQueriesGetTagsTagVm) Get() *FilterListsDirectoryApplicationQueriesGetTagsTagVm {
	return v.value
}

func (v *NullableFilterListsDirectoryApplicationQueriesGetTagsTagVm) Set(val *FilterListsDirectoryApplicationQueriesGetTagsTagVm) {
	v.value = val
	v.isSet = true
}

func (v NullableFilterListsDirectoryApplicationQueriesGetTagsTagVm) IsSet() bool {
	return v.isSet
}

func (v *NullableFilterListsDirectoryApplicationQueriesGetTagsTagVm) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFilterListsDirectoryApplicationQueriesGetTagsTagVm(val *FilterListsDirectoryApplicationQueriesGetTagsTagVm) *NullableFilterListsDirectoryApplicationQueriesGetTagsTagVm {
	return &NullableFilterListsDirectoryApplicationQueriesGetTagsTagVm{value: val, isSet: true}
}

func (v NullableFilterListsDirectoryApplicationQueriesGetTagsTagVm) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFilterListsDirectoryApplicationQueriesGetTagsTagVm) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


