/*
FilterLists Directory API

An ASP.NET Core API serving the core FilterList information.

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// FilterListsDirectoryApiContractsModelsListVm struct for FilterListsDirectoryApiContractsModelsListVm
type FilterListsDirectoryApiContractsModelsListVm struct {
	// The identifier.
	Id *int64 `json:"id,omitempty"`
	// The unique name in title case.
	Name *string `json:"name,omitempty"`
	// The brief description in English (preferably quoted from the project).
	Description NullableString `json:"description,omitempty"`
	// The identifier of the License under which this FilterList is released.
	LicenseId *int64 `json:"licenseId,omitempty"`
	// The identifiers of the Syntaxes implemented by this FilterList.
	SyntaxIds []int64 `json:"syntaxIds,omitempty"`
	// The identifiers of the Languages targeted by this FilterList.
	LanguageIds []int64 `json:"languageIds,omitempty"`
	// The identifiers of the Tags applied to this FilterList.
	TagIds []int64 `json:"tagIds,omitempty"`
	// The primary view URL.
	PrimaryViewUrl NullableString `json:"primaryViewUrl,omitempty"`
	// The identifiers of the Maintainers of this FilterList.
	MaintainerIds []int64 `json:"maintainerIds,omitempty"`
}

// NewFilterListsDirectoryApiContractsModelsListVm instantiates a new FilterListsDirectoryApiContractsModelsListVm object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFilterListsDirectoryApiContractsModelsListVm() *FilterListsDirectoryApiContractsModelsListVm {
	this := FilterListsDirectoryApiContractsModelsListVm{}
	return &this
}

// NewFilterListsDirectoryApiContractsModelsListVmWithDefaults instantiates a new FilterListsDirectoryApiContractsModelsListVm object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFilterListsDirectoryApiContractsModelsListVmWithDefaults() *FilterListsDirectoryApiContractsModelsListVm {
	this := FilterListsDirectoryApiContractsModelsListVm{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *FilterListsDirectoryApiContractsModelsListVm) GetId() int64 {
	if o == nil || isNil(o.Id) {
		var ret int64
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FilterListsDirectoryApiContractsModelsListVm) GetIdOk() (*int64, bool) {
	if o == nil || isNil(o.Id) {
    return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *FilterListsDirectoryApiContractsModelsListVm) HasId() bool {
	if o != nil && !isNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given int64 and assigns it to the Id field.
func (o *FilterListsDirectoryApiContractsModelsListVm) SetId(v int64) {
	o.Id = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *FilterListsDirectoryApiContractsModelsListVm) GetName() string {
	if o == nil || isNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FilterListsDirectoryApiContractsModelsListVm) GetNameOk() (*string, bool) {
	if o == nil || isNil(o.Name) {
    return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *FilterListsDirectoryApiContractsModelsListVm) HasName() bool {
	if o != nil && !isNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *FilterListsDirectoryApiContractsModelsListVm) SetName(v string) {
	o.Name = &v
}

// GetDescription returns the Description field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *FilterListsDirectoryApiContractsModelsListVm) GetDescription() string {
	if o == nil || isNil(o.Description.Get()) {
		var ret string
		return ret
	}
	return *o.Description.Get()
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *FilterListsDirectoryApiContractsModelsListVm) GetDescriptionOk() (*string, bool) {
	if o == nil {
    return nil, false
	}
	return o.Description.Get(), o.Description.IsSet()
}

// HasDescription returns a boolean if a field has been set.
func (o *FilterListsDirectoryApiContractsModelsListVm) HasDescription() bool {
	if o != nil && o.Description.IsSet() {
		return true
	}

	return false
}

// SetDescription gets a reference to the given NullableString and assigns it to the Description field.
func (o *FilterListsDirectoryApiContractsModelsListVm) SetDescription(v string) {
	o.Description.Set(&v)
}
// SetDescriptionNil sets the value for Description to be an explicit nil
func (o *FilterListsDirectoryApiContractsModelsListVm) SetDescriptionNil() {
	o.Description.Set(nil)
}

// UnsetDescription ensures that no value is present for Description, not even an explicit nil
func (o *FilterListsDirectoryApiContractsModelsListVm) UnsetDescription() {
	o.Description.Unset()
}

// GetLicenseId returns the LicenseId field value if set, zero value otherwise.
func (o *FilterListsDirectoryApiContractsModelsListVm) GetLicenseId() int64 {
	if o == nil || isNil(o.LicenseId) {
		var ret int64
		return ret
	}
	return *o.LicenseId
}

// GetLicenseIdOk returns a tuple with the LicenseId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FilterListsDirectoryApiContractsModelsListVm) GetLicenseIdOk() (*int64, bool) {
	if o == nil || isNil(o.LicenseId) {
    return nil, false
	}
	return o.LicenseId, true
}

// HasLicenseId returns a boolean if a field has been set.
func (o *FilterListsDirectoryApiContractsModelsListVm) HasLicenseId() bool {
	if o != nil && !isNil(o.LicenseId) {
		return true
	}

	return false
}

// SetLicenseId gets a reference to the given int64 and assigns it to the LicenseId field.
func (o *FilterListsDirectoryApiContractsModelsListVm) SetLicenseId(v int64) {
	o.LicenseId = &v
}

// GetSyntaxIds returns the SyntaxIds field value if set, zero value otherwise.
func (o *FilterListsDirectoryApiContractsModelsListVm) GetSyntaxIds() []int64 {
	if o == nil || isNil(o.SyntaxIds) {
		var ret []int64
		return ret
	}
	return o.SyntaxIds
}

// GetSyntaxIdsOk returns a tuple with the SyntaxIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FilterListsDirectoryApiContractsModelsListVm) GetSyntaxIdsOk() ([]int64, bool) {
	if o == nil || isNil(o.SyntaxIds) {
    return nil, false
	}
	return o.SyntaxIds, true
}

// HasSyntaxIds returns a boolean if a field has been set.
func (o *FilterListsDirectoryApiContractsModelsListVm) HasSyntaxIds() bool {
	if o != nil && !isNil(o.SyntaxIds) {
		return true
	}

	return false
}

// SetSyntaxIds gets a reference to the given []int64 and assigns it to the SyntaxIds field.
func (o *FilterListsDirectoryApiContractsModelsListVm) SetSyntaxIds(v []int64) {
	o.SyntaxIds = v
}

// GetLanguageIds returns the LanguageIds field value if set, zero value otherwise.
func (o *FilterListsDirectoryApiContractsModelsListVm) GetLanguageIds() []int64 {
	if o == nil || isNil(o.LanguageIds) {
		var ret []int64
		return ret
	}
	return o.LanguageIds
}

// GetLanguageIdsOk returns a tuple with the LanguageIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FilterListsDirectoryApiContractsModelsListVm) GetLanguageIdsOk() ([]int64, bool) {
	if o == nil || isNil(o.LanguageIds) {
    return nil, false
	}
	return o.LanguageIds, true
}

// HasLanguageIds returns a boolean if a field has been set.
func (o *FilterListsDirectoryApiContractsModelsListVm) HasLanguageIds() bool {
	if o != nil && !isNil(o.LanguageIds) {
		return true
	}

	return false
}

// SetLanguageIds gets a reference to the given []int64 and assigns it to the LanguageIds field.
func (o *FilterListsDirectoryApiContractsModelsListVm) SetLanguageIds(v []int64) {
	o.LanguageIds = v
}

// GetTagIds returns the TagIds field value if set, zero value otherwise.
func (o *FilterListsDirectoryApiContractsModelsListVm) GetTagIds() []int64 {
	if o == nil || isNil(o.TagIds) {
		var ret []int64
		return ret
	}
	return o.TagIds
}

// GetTagIdsOk returns a tuple with the TagIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FilterListsDirectoryApiContractsModelsListVm) GetTagIdsOk() ([]int64, bool) {
	if o == nil || isNil(o.TagIds) {
    return nil, false
	}
	return o.TagIds, true
}

// HasTagIds returns a boolean if a field has been set.
func (o *FilterListsDirectoryApiContractsModelsListVm) HasTagIds() bool {
	if o != nil && !isNil(o.TagIds) {
		return true
	}

	return false
}

// SetTagIds gets a reference to the given []int64 and assigns it to the TagIds field.
func (o *FilterListsDirectoryApiContractsModelsListVm) SetTagIds(v []int64) {
	o.TagIds = v
}

// GetPrimaryViewUrl returns the PrimaryViewUrl field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *FilterListsDirectoryApiContractsModelsListVm) GetPrimaryViewUrl() string {
	if o == nil || isNil(o.PrimaryViewUrl.Get()) {
		var ret string
		return ret
	}
	return *o.PrimaryViewUrl.Get()
}

// GetPrimaryViewUrlOk returns a tuple with the PrimaryViewUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *FilterListsDirectoryApiContractsModelsListVm) GetPrimaryViewUrlOk() (*string, bool) {
	if o == nil {
    return nil, false
	}
	return o.PrimaryViewUrl.Get(), o.PrimaryViewUrl.IsSet()
}

// HasPrimaryViewUrl returns a boolean if a field has been set.
func (o *FilterListsDirectoryApiContractsModelsListVm) HasPrimaryViewUrl() bool {
	if o != nil && o.PrimaryViewUrl.IsSet() {
		return true
	}

	return false
}

// SetPrimaryViewUrl gets a reference to the given NullableString and assigns it to the PrimaryViewUrl field.
func (o *FilterListsDirectoryApiContractsModelsListVm) SetPrimaryViewUrl(v string) {
	o.PrimaryViewUrl.Set(&v)
}
// SetPrimaryViewUrlNil sets the value for PrimaryViewUrl to be an explicit nil
func (o *FilterListsDirectoryApiContractsModelsListVm) SetPrimaryViewUrlNil() {
	o.PrimaryViewUrl.Set(nil)
}

// UnsetPrimaryViewUrl ensures that no value is present for PrimaryViewUrl, not even an explicit nil
func (o *FilterListsDirectoryApiContractsModelsListVm) UnsetPrimaryViewUrl() {
	o.PrimaryViewUrl.Unset()
}

// GetMaintainerIds returns the MaintainerIds field value if set, zero value otherwise.
func (o *FilterListsDirectoryApiContractsModelsListVm) GetMaintainerIds() []int64 {
	if o == nil || isNil(o.MaintainerIds) {
		var ret []int64
		return ret
	}
	return o.MaintainerIds
}

// GetMaintainerIdsOk returns a tuple with the MaintainerIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FilterListsDirectoryApiContractsModelsListVm) GetMaintainerIdsOk() ([]int64, bool) {
	if o == nil || isNil(o.MaintainerIds) {
    return nil, false
	}
	return o.MaintainerIds, true
}

// HasMaintainerIds returns a boolean if a field has been set.
func (o *FilterListsDirectoryApiContractsModelsListVm) HasMaintainerIds() bool {
	if o != nil && !isNil(o.MaintainerIds) {
		return true
	}

	return false
}

// SetMaintainerIds gets a reference to the given []int64 and assigns it to the MaintainerIds field.
func (o *FilterListsDirectoryApiContractsModelsListVm) SetMaintainerIds(v []int64) {
	o.MaintainerIds = v
}

func (o FilterListsDirectoryApiContractsModelsListVm) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !isNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if o.Description.IsSet() {
		toSerialize["description"] = o.Description.Get()
	}
	if !isNil(o.LicenseId) {
		toSerialize["licenseId"] = o.LicenseId
	}
	if !isNil(o.SyntaxIds) {
		toSerialize["syntaxIds"] = o.SyntaxIds
	}
	if !isNil(o.LanguageIds) {
		toSerialize["languageIds"] = o.LanguageIds
	}
	if !isNil(o.TagIds) {
		toSerialize["tagIds"] = o.TagIds
	}
	if o.PrimaryViewUrl.IsSet() {
		toSerialize["primaryViewUrl"] = o.PrimaryViewUrl.Get()
	}
	if !isNil(o.MaintainerIds) {
		toSerialize["maintainerIds"] = o.MaintainerIds
	}
	return json.Marshal(toSerialize)
}

type NullableFilterListsDirectoryApiContractsModelsListVm struct {
	value *FilterListsDirectoryApiContractsModelsListVm
	isSet bool
}

func (v NullableFilterListsDirectoryApiContractsModelsListVm) Get() *FilterListsDirectoryApiContractsModelsListVm {
	return v.value
}

func (v *NullableFilterListsDirectoryApiContractsModelsListVm) Set(val *FilterListsDirectoryApiContractsModelsListVm) {
	v.value = val
	v.isSet = true
}

func (v NullableFilterListsDirectoryApiContractsModelsListVm) IsSet() bool {
	return v.isSet
}

func (v *NullableFilterListsDirectoryApiContractsModelsListVm) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFilterListsDirectoryApiContractsModelsListVm(val *FilterListsDirectoryApiContractsModelsListVm) *NullableFilterListsDirectoryApiContractsModelsListVm {
	return &NullableFilterListsDirectoryApiContractsModelsListVm{value: val, isSet: true}
}

func (v NullableFilterListsDirectoryApiContractsModelsListVm) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFilterListsDirectoryApiContractsModelsListVm) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


