/*
FilterLists Directory API

An ASP.NET Core API serving the core FilterList information.

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// FilterListsDirectoryApplicationQueriesGetSyntaxesSyntaxVm struct for FilterListsDirectoryApplicationQueriesGetSyntaxesSyntaxVm
type FilterListsDirectoryApplicationQueriesGetSyntaxesSyntaxVm struct {
	// The identifier.
	Id *int64 `json:"id,omitempty"`
	// The unique name.
	Name *string `json:"name,omitempty"`
	// The description.
	Description NullableString `json:"description,omitempty"`
	// The URL of the home page.
	Url NullableString `json:"url,omitempty"`
	// The identifiers of the FilterLists implementing this Syntax.
	FilterListIds []int64 `json:"filterListIds,omitempty"`
	// The identifiers of the Software that supports this Syntax.
	SoftwareIds []int64 `json:"softwareIds,omitempty"`
}

// NewFilterListsDirectoryApplicationQueriesGetSyntaxesSyntaxVm instantiates a new FilterListsDirectoryApplicationQueriesGetSyntaxesSyntaxVm object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFilterListsDirectoryApplicationQueriesGetSyntaxesSyntaxVm() *FilterListsDirectoryApplicationQueriesGetSyntaxesSyntaxVm {
	this := FilterListsDirectoryApplicationQueriesGetSyntaxesSyntaxVm{}
	return &this
}

// NewFilterListsDirectoryApplicationQueriesGetSyntaxesSyntaxVmWithDefaults instantiates a new FilterListsDirectoryApplicationQueriesGetSyntaxesSyntaxVm object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFilterListsDirectoryApplicationQueriesGetSyntaxesSyntaxVmWithDefaults() *FilterListsDirectoryApplicationQueriesGetSyntaxesSyntaxVm {
	this := FilterListsDirectoryApplicationQueriesGetSyntaxesSyntaxVm{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *FilterListsDirectoryApplicationQueriesGetSyntaxesSyntaxVm) GetId() int64 {
	if o == nil || isNil(o.Id) {
		var ret int64
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FilterListsDirectoryApplicationQueriesGetSyntaxesSyntaxVm) GetIdOk() (*int64, bool) {
	if o == nil || isNil(o.Id) {
    return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *FilterListsDirectoryApplicationQueriesGetSyntaxesSyntaxVm) HasId() bool {
	if o != nil && !isNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given int64 and assigns it to the Id field.
func (o *FilterListsDirectoryApplicationQueriesGetSyntaxesSyntaxVm) SetId(v int64) {
	o.Id = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *FilterListsDirectoryApplicationQueriesGetSyntaxesSyntaxVm) GetName() string {
	if o == nil || isNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FilterListsDirectoryApplicationQueriesGetSyntaxesSyntaxVm) GetNameOk() (*string, bool) {
	if o == nil || isNil(o.Name) {
    return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *FilterListsDirectoryApplicationQueriesGetSyntaxesSyntaxVm) HasName() bool {
	if o != nil && !isNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *FilterListsDirectoryApplicationQueriesGetSyntaxesSyntaxVm) SetName(v string) {
	o.Name = &v
}

// GetDescription returns the Description field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *FilterListsDirectoryApplicationQueriesGetSyntaxesSyntaxVm) GetDescription() string {
	if o == nil || isNil(o.Description.Get()) {
		var ret string
		return ret
	}
	return *o.Description.Get()
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *FilterListsDirectoryApplicationQueriesGetSyntaxesSyntaxVm) GetDescriptionOk() (*string, bool) {
	if o == nil {
    return nil, false
	}
	return o.Description.Get(), o.Description.IsSet()
}

// HasDescription returns a boolean if a field has been set.
func (o *FilterListsDirectoryApplicationQueriesGetSyntaxesSyntaxVm) HasDescription() bool {
	if o != nil && o.Description.IsSet() {
		return true
	}

	return false
}

// SetDescription gets a reference to the given NullableString and assigns it to the Description field.
func (o *FilterListsDirectoryApplicationQueriesGetSyntaxesSyntaxVm) SetDescription(v string) {
	o.Description.Set(&v)
}
// SetDescriptionNil sets the value for Description to be an explicit nil
func (o *FilterListsDirectoryApplicationQueriesGetSyntaxesSyntaxVm) SetDescriptionNil() {
	o.Description.Set(nil)
}

// UnsetDescription ensures that no value is present for Description, not even an explicit nil
func (o *FilterListsDirectoryApplicationQueriesGetSyntaxesSyntaxVm) UnsetDescription() {
	o.Description.Unset()
}

// GetUrl returns the Url field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *FilterListsDirectoryApplicationQueriesGetSyntaxesSyntaxVm) GetUrl() string {
	if o == nil || isNil(o.Url.Get()) {
		var ret string
		return ret
	}
	return *o.Url.Get()
}

// GetUrlOk returns a tuple with the Url field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *FilterListsDirectoryApplicationQueriesGetSyntaxesSyntaxVm) GetUrlOk() (*string, bool) {
	if o == nil {
    return nil, false
	}
	return o.Url.Get(), o.Url.IsSet()
}

// HasUrl returns a boolean if a field has been set.
func (o *FilterListsDirectoryApplicationQueriesGetSyntaxesSyntaxVm) HasUrl() bool {
	if o != nil && o.Url.IsSet() {
		return true
	}

	return false
}

// SetUrl gets a reference to the given NullableString and assigns it to the Url field.
func (o *FilterListsDirectoryApplicationQueriesGetSyntaxesSyntaxVm) SetUrl(v string) {
	o.Url.Set(&v)
}
// SetUrlNil sets the value for Url to be an explicit nil
func (o *FilterListsDirectoryApplicationQueriesGetSyntaxesSyntaxVm) SetUrlNil() {
	o.Url.Set(nil)
}

// UnsetUrl ensures that no value is present for Url, not even an explicit nil
func (o *FilterListsDirectoryApplicationQueriesGetSyntaxesSyntaxVm) UnsetUrl() {
	o.Url.Unset()
}

// GetFilterListIds returns the FilterListIds field value if set, zero value otherwise.
func (o *FilterListsDirectoryApplicationQueriesGetSyntaxesSyntaxVm) GetFilterListIds() []int64 {
	if o == nil || isNil(o.FilterListIds) {
		var ret []int64
		return ret
	}
	return o.FilterListIds
}

// GetFilterListIdsOk returns a tuple with the FilterListIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FilterListsDirectoryApplicationQueriesGetSyntaxesSyntaxVm) GetFilterListIdsOk() ([]int64, bool) {
	if o == nil || isNil(o.FilterListIds) {
    return nil, false
	}
	return o.FilterListIds, true
}

// HasFilterListIds returns a boolean if a field has been set.
func (o *FilterListsDirectoryApplicationQueriesGetSyntaxesSyntaxVm) HasFilterListIds() bool {
	if o != nil && !isNil(o.FilterListIds) {
		return true
	}

	return false
}

// SetFilterListIds gets a reference to the given []int64 and assigns it to the FilterListIds field.
func (o *FilterListsDirectoryApplicationQueriesGetSyntaxesSyntaxVm) SetFilterListIds(v []int64) {
	o.FilterListIds = v
}

// GetSoftwareIds returns the SoftwareIds field value if set, zero value otherwise.
func (o *FilterListsDirectoryApplicationQueriesGetSyntaxesSyntaxVm) GetSoftwareIds() []int64 {
	if o == nil || isNil(o.SoftwareIds) {
		var ret []int64
		return ret
	}
	return o.SoftwareIds
}

// GetSoftwareIdsOk returns a tuple with the SoftwareIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FilterListsDirectoryApplicationQueriesGetSyntaxesSyntaxVm) GetSoftwareIdsOk() ([]int64, bool) {
	if o == nil || isNil(o.SoftwareIds) {
    return nil, false
	}
	return o.SoftwareIds, true
}

// HasSoftwareIds returns a boolean if a field has been set.
func (o *FilterListsDirectoryApplicationQueriesGetSyntaxesSyntaxVm) HasSoftwareIds() bool {
	if o != nil && !isNil(o.SoftwareIds) {
		return true
	}

	return false
}

// SetSoftwareIds gets a reference to the given []int64 and assigns it to the SoftwareIds field.
func (o *FilterListsDirectoryApplicationQueriesGetSyntaxesSyntaxVm) SetSoftwareIds(v []int64) {
	o.SoftwareIds = v
}

func (o FilterListsDirectoryApplicationQueriesGetSyntaxesSyntaxVm) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !isNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if o.Description.IsSet() {
		toSerialize["description"] = o.Description.Get()
	}
	if o.Url.IsSet() {
		toSerialize["url"] = o.Url.Get()
	}
	if !isNil(o.FilterListIds) {
		toSerialize["filterListIds"] = o.FilterListIds
	}
	if !isNil(o.SoftwareIds) {
		toSerialize["softwareIds"] = o.SoftwareIds
	}
	return json.Marshal(toSerialize)
}

type NullableFilterListsDirectoryApplicationQueriesGetSyntaxesSyntaxVm struct {
	value *FilterListsDirectoryApplicationQueriesGetSyntaxesSyntaxVm
	isSet bool
}

func (v NullableFilterListsDirectoryApplicationQueriesGetSyntaxesSyntaxVm) Get() *FilterListsDirectoryApplicationQueriesGetSyntaxesSyntaxVm {
	return v.value
}

func (v *NullableFilterListsDirectoryApplicationQueriesGetSyntaxesSyntaxVm) Set(val *FilterListsDirectoryApplicationQueriesGetSyntaxesSyntaxVm) {
	v.value = val
	v.isSet = true
}

func (v NullableFilterListsDirectoryApplicationQueriesGetSyntaxesSyntaxVm) IsSet() bool {
	return v.isSet
}

func (v *NullableFilterListsDirectoryApplicationQueriesGetSyntaxesSyntaxVm) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFilterListsDirectoryApplicationQueriesGetSyntaxesSyntaxVm(val *FilterListsDirectoryApplicationQueriesGetSyntaxesSyntaxVm) *NullableFilterListsDirectoryApplicationQueriesGetSyntaxesSyntaxVm {
	return &NullableFilterListsDirectoryApplicationQueriesGetSyntaxesSyntaxVm{value: val, isSet: true}
}

func (v NullableFilterListsDirectoryApplicationQueriesGetSyntaxesSyntaxVm) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFilterListsDirectoryApplicationQueriesGetSyntaxesSyntaxVm) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


